//===----------------------------------------------------------------------===//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//

// Modifications Copyright (C) 2026 Advanced Micro Devices, Inc. All rights reserved.
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.

// UNSUPPORTED: pre-gfx1250
// UNSUPPORTED: nvcc, nvhpc, nvc++

// <cuda/barrier>

// Verify multiple real cuda::memcpy_async producers accumulate on the same
// barrier phase. Tx completions are generated by the async copy dispatch path.

#include <cuda/barrier>
#include <cuda/std/utility>
#include "test_macros.h"

constexpr int k_count = 4;
constexpr int k_copies = 4;

__device__ __attribute__((aligned(16))) int g_src[k_count * k_copies] = {
  200, 201, 202, 203,
  204, 205, 206, 207,
  208, 209, 210, 211,
  212, 213, 214, 215
};

__device__ int test()
{
  __shared__ cuda::barrier<cuda::thread_scope_block> bar;
  __shared__ __attribute__((aligned(16))) int dest[k_count * k_copies];

  if (threadIdx.x == 0) {
    init(&bar, 1);
    for (int i = 0; i < k_count * k_copies; ++i) {
      dest[i] = -1;
    }

    for (int copy = 0; copy < k_copies; ++copy) {
      cuda::memcpy_async(
        &dest[copy * k_count],
        &g_src[copy * k_count],
        cuda::aligned_size_t<16>(sizeof(int) * k_count),
        bar);
    }

    auto token = bar.arrive();
    bar.wait(cuda::std::move(token));

    for (int i = 0; i < k_count * k_copies; ++i) {
      if (dest[i] != g_src[i]) {
        return 1;
      }
    }
  }

  return 0;
}

int main(int, char**)
{
  NV_IF_TARGET(NV_IS_HOST, (
    cuda_block_count = 1;
    cuda_thread_count = 1;
  ))
  NV_IF_TARGET(NV_IS_DEVICE, (return test();))
  return 0;
}