// MIT License
//
// Copyright (c) 2026 Advanced Micro Devices, Inc.
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.

#ifndef HIP_INTRINSICS_H
#define HIP_INTRINSICS_H

#include <cstdlib>
#include <filesystem>
#include <fstream>
#include <ostream>
#include <string>

#include <fmt/format.h>
#include <fmt/ostream.h>

// =============================================================================
// HIP-side __atomic_*_cuda emitter.
//
// Emits the ENTIRE 'atomic_hip_generated.h' header (header + scope blocks +
// footer) when 'codegen --hip <out>' is invoked. Three scope blocks
// ('block' / 'device' / 'system') are emitted by FormatHipScope; the
// HIP-unsupported 'cluster' scope is emitted by FormatHipScopeUnsupported
// as signature-matching static_asserts that fire at instantiation rather
// than silently mapping to AGENT / WORKGROUP. See the per-call comments
// in FormatHip() for the per-scope routing.
// =============================================================================

// Read the license text pointed to by LICENSE_FILE (set by the codegen build
// target -- see codegen/CMakeLists.txt) and stream it to 'out'. Keeping the
// license text out-of-source (as a sibling .txt) ensures hip_intrinsics.h
// carries at most one license header (its own, at the top of this file) and
// license-verification tools don't see two blocks that they'd flag as
// inconsistent. Aborts on missing / unreadable LICENSE_FILE so a
// misconfigured build fails loudly instead of silently shipping a
// license-less generated header.
inline void FormatHipEmitLicense(std::ostream& out)
{
  const char* license_file = std::getenv("LICENSE_FILE");
  if (license_file == nullptr || *license_file == '\0')
  {
    fmt::print(stderr,
               "FormatHipHeader: LICENSE_FILE env var must be set to the path of\n"
               "  codegen/generators/atomic_hip_generated.license.txt (or equivalent).\n"
               "  Set via 'cmake -E env LICENSE_FILE=... codegen --hip ...' (already\n"
               "  wired in codegen/CMakeLists.txt's libcudacxx.atomics.codegen.hip target).\n");
    std::exit(2);
  }
  std::ifstream license_stream(license_file);
  if (!license_stream.is_open())
  {
    fmt::print(stderr, "FormatHipHeader: cannot open LICENSE_FILE='{}' for reading\n", license_file);
    std::exit(2);
  }
  out << license_stream.rdbuf();
}

inline void FormatHipHeader(std::ostream& out)
{
  FormatHipEmitLicense(out);
  // Embed the path of THIS generator file into the autogen banner via
  // std::filesystem so the comment stays accurate if the file ever moves.
  // __FILE__ is an absolute path at build time; relativise against
  // 'libhipcxx' (the project root marker) for a stable in-tree path.
  std::filesystem::path generator_path = std::filesystem::path(__FILE__).lexically_normal();
  std::string generator_rel            = generator_path.string();
  if (auto pos = generator_rel.find("/codegen/"); pos != std::string::npos)
  {
    generator_rel = generator_rel.substr(pos + 1);
  }
  fmt::print(out, R"XXX(
// This is an autogenerated file. Edits will be lost on the next regeneration --
// modify {0} instead and run
//   cmake --build <build> --target libcudacxx.atomics.codegen.hip.install
// 'libcudacxx.test.atomics.codegen.hip.diff' guards against in-tree drift.
// clang-format off

#pragma once

#include <hip/hip_runtime.h>

#include <cuda/std/__type_traits/always_false.h>
#include <cuda/std/__type_traits/enable_if.h>
#include <cuda/std/__type_traits/is_signed.h>
#include <cuda/std/__type_traits/is_unsigned.h>

#include <cuda/std/__atomic/scopes.h>
#include <cuda/std/__atomic/functions/cuda_local.h>

#include <cuda/std/__cccl/prologue.h>

_CCCL_BEGIN_NAMESPACE_CUDA_STD
)XXX",
             generator_rel);
}

inline void FormatHipFooter(std::ostream& out)
{
  out << R"XXX(
_CCCL_END_NAMESPACE_CUDA_STD

#include <cuda/std/__cccl/epilogue.h>
)XXX";
}

// Helper for the compare_exchange body: 'system' scope distinguishes weak vs
// strong CAS via the named '__is_weak' parameter; 'block' / 'device' always
// emit weak CAS (anonymous bool param). Returning the body fragment as a
// string lets the compare_exchange template be ONE fmt::format call across
// both shapes (per g26 review on PR #217). Mirrors the upstream reviewer's
// suggested 'checkWeak()' helper verbatim.
inline std::string FormatHipCheckWeak(const std::string& scope_macro, bool cas_branches_on_weak)
{
  if (cas_branches_on_weak)
  {
    return fmt::format(R"XXX(if(__is_weak)
            return __hip_atomic_compare_exchange_weak(__ptr, __expected, __desired, __success_memorder, __failure_memorder, {0});
        else
            return __hip_atomic_compare_exchange_strong(__ptr, __expected, __desired, __success_memorder, __failure_memorder, {0});)XXX",
                       scope_macro);
  }
  return fmt::format(
    "return __hip_atomic_compare_exchange_weak(__ptr, __expected, __desired, __success_memorder, __failure_memorder, "
    "{0});",
    scope_macro);
}

inline void FormatHipScope(std::ostream& out,
                           const std::string& scope_tag,
                           const std::string& fence_func,
                           const std::string& scope_macro,
                           bool has_ptr_fetch_sub,
                           bool cas_branches_on_weak)
{
  // CAS signature differs by scope: 'system' takes a named '__is_weak' bool;
  // 'block' / 'device' take an anonymous bool (always-weak CAS). The static
  // assertion message also differs ('compare_exchange_*' vs
  // 'compare_exchange_weak') so it stays accurate in either shape.
  const std::string cas_param       = cas_branches_on_weak ? "bool __is_weak" : "bool";
  const std::string cas_assert_kind = cas_branches_on_weak ? "*" : "weak";
  const std::string cas_body        = FormatHipCheckWeak(scope_macro, cas_branches_on_weak);

  // The 6 same-shape fetch ops (and/or/xor/add/max/min) are programmatically
  // assembled as a single chunk so the giant fmt::format below substitutes
  // them via one {fetch_ops_body} placeholder instead of N separate fmt
  // calls (g25 / g27 review).
  std::string fetch_ops_body;
  for (const char* op : {"and", "or", "xor", "add", "max", "min"})
  {
    fetch_ops_body += fmt::format(R"XXX(
template<class _Type>
[[nodiscard]] static inline _CCCL_DEVICE _Type __atomic_fetch_{op}_cuda(volatile _Type *__ptr, _Type __val, int __memorder, {scope_tag}) {{
    _Type __ret;
    if (__cuda_fetch_{op}_weak_if_local(__ptr, __val, &__ret)) return __ret;
    return __hip_atomic_fetch_{op}(__ptr, __val, __memorder, {scope_macro});
}}
)XXX",
                                  fmt::arg("op", op),
                                  fmt::arg("scope_tag", scope_tag),
                                  fmt::arg("scope_macro", scope_macro));
  }

  // Optional pointer fetch_sub: only emitted for device/system scope. The
  // in-tree block-scope section omits it for upstream parity. When absent
  // we leave NO blank line between the ptr fetch_add and the next scope
  // block's leading newline -- matches the byte-exact in-tree shape.
  const std::string ptr_fetch_sub = has_ptr_fetch_sub
                                    ? fmt::format(R"XXX(template<class _Type>
[[nodiscard]] static inline _CCCL_DEVICE _Type* __atomic_fetch_sub_cuda(_Type *volatile *__ptr, ptrdiff_t __val, int __memorder, {0}) {{
    return __hip_atomic_fetch_add(__ptr, -__val, __memorder, {1});
}}
)XXX",
                                                  scope_tag,
                                                  scope_macro)
                                    : "";

  // Single fmt::format for the entire scope block (g25 / g27 review).
  // Placeholders use named args for readability across this many fields.
  // The '[[maybe_unused]] int __memorder' on thread_fence is upstream-API
  // parity (callers pass __ATOMIC_* constants) -- the HIP body uses scope-
  // based __threadfence_*() builtins that don't take an order.
  fmt::print(out, R"XXX(
static inline _CCCL_DEVICE void __atomic_thread_fence_cuda([[maybe_unused]] int __memorder, {scope_tag}) {{
    {fence_func}();
}}

template<class _Type>
static inline _CCCL_DEVICE void __atomic_load_cuda(const volatile _Type *__ptr, _Type& __dst, int __memorder, {scope_tag}) {{
    if constexpr (sizeof(_Type) > 8) {{
        static_assert(::cuda::std::__always_false_v<_Type>,
                      ">64-bit atomic load is not supported on HIP (clang HIP __hip_atomic_load caps at 64-bit)");
    }} else {{
        if (__cuda_load_weak_if_local(__ptr, &__dst, sizeof(_Type))) return;
        __dst = __hip_atomic_load(__ptr, __memorder, {scope_macro});
    }}
}}

template<class _Type>
static inline _CCCL_DEVICE void __atomic_store_cuda(volatile _Type *__ptr, _Type& __val, int __memorder, {scope_tag}) {{
    if constexpr (sizeof(_Type) > 8) {{
        static_assert(::cuda::std::__always_false_v<_Type>,
                      ">64-bit atomic store is not supported on HIP (clang HIP __hip_atomic_store caps at 64-bit)");
    }} else {{
        if (__cuda_store_weak_if_local(__ptr, &__val, sizeof(_Type))) return;
        __hip_atomic_store(__ptr, __val, __memorder, {scope_macro});
    }}
}}

template<class _Type>
[[nodiscard]] static inline _CCCL_DEVICE bool __atomic_compare_exchange_cuda(volatile _Type *__ptr, _Type *__expected, const _Type __desired, {cas_param}, int __success_memorder, int __failure_memorder, {scope_tag}) {{
    if constexpr (sizeof(_Type) > 8) {{
        static_assert(::cuda::std::__always_false_v<_Type>,
                      ">64-bit atomic compare_exchange is not supported on HIP (clang HIP __hip_atomic_compare_exchange_{cas_assert_kind} caps at 64-bit)");
        return false;
    }} else {{
        bool __success;
        if (__cuda_compare_exchange_weak_if_local(__ptr, __expected, &__desired, &__success)) return __success;
        {cas_body}
    }}
}}

template<class _Type>
static inline _CCCL_DEVICE void __atomic_exchange_cuda(volatile _Type* __ptr, _Type& __old, _Type __new, int __memorder, {scope_tag}) {{
    if constexpr (sizeof(_Type) > 8) {{
        static_assert(::cuda::std::__always_false_v<_Type>,
                      ">64-bit atomic exchange is not supported on HIP (clang HIP __hip_atomic_exchange caps at 64-bit)");
    }} else {{
        if (__cuda_exchange_weak_if_local(__ptr, &__new, &__old)) return;
        __old = __hip_atomic_exchange(__ptr, __new, __memorder, {scope_macro});
    }}
}}
{fetch_ops_body}
template<class _Type>
[[nodiscard]] static inline _CCCL_DEVICE _Type __atomic_fetch_sub_cuda(volatile _Type *__ptr, _Type __val, int __memorder, {scope_tag}) {{
    _Type __ret;
    if (__cuda_fetch_sub_weak_if_local(__ptr, __val, &__ret)) return __ret;
    return __hip_atomic_fetch_add(__ptr, -__val, __memorder, {scope_macro});
}}

template<class _Type>
[[nodiscard]] static inline _CCCL_DEVICE _Type* __atomic_fetch_add_cuda(_Type *volatile *__ptr, ptrdiff_t __val, int __memorder, {scope_tag}) {{
    return __hip_atomic_fetch_add(__ptr, __val, __memorder, {scope_macro});
}}
{ptr_fetch_sub})XXX",
             fmt::arg("scope_tag", scope_tag),
             fmt::arg("fence_func", fence_func),
             fmt::arg("scope_macro", scope_macro),
             fmt::arg("cas_param", cas_param),
             fmt::arg("cas_assert_kind", cas_assert_kind),
             fmt::arg("cas_body", cas_body),
             fmt::arg("fetch_ops_body", fetch_ops_body),
             fmt::arg("ptr_fetch_sub", ptr_fetch_sub));
}

// Emit a scope block whose every overload is a static_assert at instantiation.
// Used for HIP-unsupported scope tags (today: 'cluster' -- AMDGCN has no
// cluster-scope equivalent and any silent mapping would lie about what was
// actually compiled). The signatures match the supported scopes 1:1 so that
// overload resolution from the public 'cuda::atomic_ref<T, scope>' API picks
// up THESE overloads on cluster scope and produces the static_assert message
// at the right call site, instead of a "no matching function" template-tower.
//
// Body shape: 'static_assert(__always_false_v<_Type>, "<msg>")' is
// value-dependent on the template parameter, so it is NOT evaluated at
// template definition time -- only when the function is instantiated. The
// thread_fence template is a special case (non-template upstream; here we
// add a _Dummy = void parameter to keep the assert value-dependent and
// defer it to instantiation).
inline void FormatHipScopeUnsupported(std::ostream& out, const std::string& scope_tag, const std::string& reason)
{
  // The 7 fetch ops (and/or/xor/add/max/min/sub) plus pointer ops are
  // assembled programmatically and substituted via one placeholder, same
  // pattern as FormatHipScope.
  std::string fetch_ops_body;
  for (const char* op : {"and", "or", "xor", "add", "max", "min", "sub"})
  {
    fetch_ops_body += fmt::format(R"XXX(
template<class _Type>
[[nodiscard]] static inline _CCCL_DEVICE _Type __atomic_fetch_{op}_cuda(volatile _Type *, _Type, int, {scope_tag}) {{
    static_assert(::cuda::std::__always_false_v<_Type>, "{reason}");
    return _Type{{}};
}}
)XXX",
                                  fmt::arg("op", op),
                                  fmt::arg("scope_tag", scope_tag),
                                  fmt::arg("reason", reason));
  }

  // Single fmt::format for the entire unsupported-scope block (g27 review).
  fmt::print(out, R"XXX(
template <class _Dummy = void>
static inline _CCCL_DEVICE void __atomic_thread_fence_cuda(int, {scope_tag}) {{
    static_assert(::cuda::std::__always_false_v<_Dummy>, "{reason}");
}}

template<class _Type>
static inline _CCCL_DEVICE void __atomic_load_cuda(const volatile _Type *, _Type&, int, {scope_tag}) {{
    static_assert(::cuda::std::__always_false_v<_Type>, "{reason}");
}}

template<class _Type>
static inline _CCCL_DEVICE void __atomic_store_cuda(volatile _Type *, _Type&, int, {scope_tag}) {{
    static_assert(::cuda::std::__always_false_v<_Type>, "{reason}");
}}

template<class _Type>
[[nodiscard]] static inline _CCCL_DEVICE bool __atomic_compare_exchange_cuda(volatile _Type *, _Type *, const _Type, bool, int, int, {scope_tag}) {{
    static_assert(::cuda::std::__always_false_v<_Type>, "{reason}");
    return false;
}}

template<class _Type>
static inline _CCCL_DEVICE void __atomic_exchange_cuda(volatile _Type*, _Type&, _Type, int, {scope_tag}) {{
    static_assert(::cuda::std::__always_false_v<_Type>, "{reason}");
}}
{fetch_ops_body}
template<class _Type>
[[nodiscard]] static inline _CCCL_DEVICE _Type* __atomic_fetch_add_cuda(_Type *volatile *, ptrdiff_t, int, {scope_tag}) {{
    static_assert(::cuda::std::__always_false_v<_Type>, "{reason}");
    return nullptr;
}}
template<class _Type>
[[nodiscard]] static inline _CCCL_DEVICE _Type* __atomic_fetch_sub_cuda(_Type *volatile *, ptrdiff_t, int, {scope_tag}) {{
    static_assert(::cuda::std::__always_false_v<_Type>, "{reason}");
    return nullptr;
}}
)XXX",
             fmt::arg("scope_tag", scope_tag),
             fmt::arg("reason", reason),
             fmt::arg("fetch_ops_body", fetch_ops_body));
}

inline void FormatHip(std::ostream& out)
{
  FormatHipHeader(out);
  FormatHipScope(out,
                 /*scope_tag=*/"__thread_scope_block_tag",
                 /*fence_func=*/"__threadfence_block",
                 /*scope_macro=*/"__HIP_MEMORY_SCOPE_WORKGROUP",
                 /*has_ptr_fetch_sub=*/false,
                 /*cas_branches_on_weak=*/false);
  // Cluster scope is HIP-unsupported (AMDGCN has no equivalent). Emit a
  // signature-matching block that static_asserts at instantiation, BEFORE
  // the device/system scopes -- ordering mirrors the upstream NV file which
  // emits cluster between block and device.
  FormatHipScopeUnsupported(out,
                            /*scope_tag=*/"__thread_scope_cluster_tag",
                            /*reason=*/"thread_scope_cluster is not supported on HIP "
                                       "(AMDGCN has no cluster-scope equivalent)");
  FormatHipScope(out,
                 /*scope_tag=*/"__thread_scope_device_tag",
                 /*fence_func=*/"__threadfence",
                 /*scope_macro=*/"__HIP_MEMORY_SCOPE_AGENT",
                 /*has_ptr_fetch_sub=*/true,
                 /*cas_branches_on_weak=*/false);
  FormatHipScope(out,
                 /*scope_tag=*/"__thread_scope_system_tag",
                 /*fence_func=*/"__threadfence_system",
                 /*scope_macro=*/"__HIP_MEMORY_SCOPE_SYSTEM",
                 /*has_ptr_fetch_sub=*/true,
                 /*cas_branches_on_weak=*/true);
  FormatHipFooter(out);
}

#endif // HIP_INTRINSICS_H
